### ISSUE TITLE
docker compose failing to start

### ISSUE THREAD

**Issue by rduivenvoorde** [elpaso/qgis-server-docker#1]
Wanting to try this container, I get:

```
[richard@oost qgis-server-docker (production)]$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'qgis-server'
[richard@oost qgis-server-docker (production)]$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

I'm on debian testing, docker version = 

```
$ docker --version
Docker version 20.10.2+dfsg1, build 2291f61
```

Googling [0] revealed I have to add a version to the yaml file, so adding `version: '3.1'` works for me:

```
version: '3.1'

services:
  qgis-server:
    image: "elpaso/qgis-server:latest"
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./qgis_projects:/qgis_projects

```

[0] https://medium.com/@abhishek.jalan84/error-the-compose-file-docker-compose-yml-is-invalid-because-dc973ceab789
[1] https://docs.docker.com/compose/compose-file/compose-versioning/#version-1
